package com.restaurante.financeiro.reconciliation.model;

public enum ReconciliationCaseClassification {
    PEDIDO_NAO_ACEITE, PEDIDO_CANCELADO, PEDIDO_NAO_ENCONTRADO,
    VALOR_DIVERGENTE, REFERENCIA_DIVERGENTE, TENANT_DIVERGENTE,
    ESTADO_FINANCEIRO_INCOMPATIVEL, ORDEM_PAGAMENTO_INEXISTENTE,
    ORDEM_PAGAMENTO_EXPIRADA, RESPOSTA_GATEWAY_INCONSISTENTE,
    NECESSITA_REEMBOLSO_EXTERNO, DADO_LEGADO, OUTRO
}
