-- data.sql DESABILITADO
-- Todo o seed de dados é gerido exclusivamente pelo DataSeeder.java (perfil dev).
-- Motivo: evitar conflito de dados duplicados e manter consistência com o modelo JPA actual.
-- Ver: src/main/java/com/restaurante/config/DataSeeder.java
