package com.restaurante.model.enums;

public enum CaixaOperadorDivergenceReasonCategory {
    OPERATOR_COUNTING_ERROR,
    CUSTOMER_CHANGE_ERROR,
    TPA_RECEIPT_MISMATCH,
    DUPLICATE_MANUAL_CONFIRMATION,
    MISSING_MANUAL_CONFIRMATION,
    WRONG_PAYMENT_METHOD_SELECTED,
    REFUND_NOT_RECORDED,
    CASH_WITHDRAWAL_NOT_RECORDED,
    DEVICE_SYNC_DELAY,
    OFFLINE_REPLAY_TIMING,
    ADMIN_CORRECTION,
    SUSPECTED_FRAUD,
    OTHER
}

