package com.restaurante.model.enums;

public enum DeliveryJobStatus {
    CREATED,
    SEARCHING_COURIER,
    COURIER_INVITED,
    COURIER_ACCEPTED,
    COURIER_REJECTED,
    ASSIGNED,
    PICKUP_READY,
    PICKED_UP,
    IN_TRANSIT,
    DELIVERED,
    CANCELLED_BY_CUSTOMER,
    CANCELLED_BY_TENANT,
    FAILED_NO_COURIER,
    FAILED_COURIER_NO_SHOW,
    FAILED_DELIVERY_PROBLEM
}

