package com.restaurante.model.enums;

public enum DeviceOfflineReplayEligibilityReason {
    STATUS_NOT_REPLAYABLE,
    COMMAND_ALREADY_APPLIED,
    COMMAND_DUPLICATE,
    IDEMPOTENCY_CONFLICT_NOT_REPLAYABLE,
    PAYLOAD_HASH_MISMATCH,
    PAYLOAD_TOO_LARGE_NOT_REPLAYABLE,
    COMMAND_TYPE_NOT_ALLOWED,
    LOCAL_REF_NOT_RESOLVABLE,
    LOCAL_REF_FAILED_DEPENDENCY,
    ORDER_ALREADY_CONFIRMED_BY_OTHER,
    SESSION_CLOSED,
    PRICE_CHANGED_NOT_REPLAYABLE,
    DEVICE_CAPABILITY_MISSING,
    PAYMENT_METHOD_NOT_ALLOWED,
    TURNO_NOT_OPEN,
    ELIGIBLE_RETRYABLE_FAILURE,
    ELIGIBLE_AFTER_DEPENDENCY_RESOLVED,
    LOW_VALUE_NOOP
}
