package com.restaurante.model.enums;

public enum DeviceCapability {
    HEARTBEAT,
    SYNC_CATALOG,
    VIEW_ORDERS,
    CREATE_ORDER,
    VIEW_PRODUCTION,
    UPDATE_PRODUCTION_STATUS,
    VIEW_PAYMENTS,
    INITIATE_PAYMENT,
    VIEW_PAYMENT_ORDER,
    CONFIRM_CASH_PAYMENT,
    CONFIRM_TPA_PAYMENT,
    MANAGE_CONSUMPTION_FUND,
    REPRINT_CONSUMPTION_DOCUMENTS,
    PRINT_RECEIPT,
    // Prompt 39.2: identificação assistida (sensível)
    LOOKUP_CONSUMPTION_BY_PHONE,
    REQUEST_ASSISTED_IDENTIFICATION_OTP,
    VERIFY_ASSISTED_IDENTIFICATION_OTP,
    LINK_CUSTOMER_TO_SESSION,
    CROSS_UNIT_ASSISTED_IDENTIFICATION,
    // Prompt 40: POS offline-first mínimo (sync seguro de comandos)
    OFFLINE_SYNC,
    OFFLINE_CREATE_ORDER,
    OFFLINE_CREATE_MANUAL_PAYMENT_ORDER,
    OFFLINE_CONFIRM_MANUAL_PAYMENT
}
