package com.restaurante.model.enums;

public enum DeviceOfflineConflictCode {
    PAYLOAD_HASH_MISMATCH,
    ENTITY_NOT_FOUND,
    SESSION_CLOSED,
    PRODUCT_INACTIVE,
    PRICE_CHANGED,
    PAYMENT_METHOD_NOT_ALLOWED,
    TURNO_NOT_OPEN,
    ORDER_ALREADY_CONFIRMED,
    DEVICE_NOT_AUTHORIZED,
    COMMAND_TYPE_NOT_ALLOWED_OFFLINE,
    IDEMPOTENCY_CONFLICT,
    LOCAL_REF_NOT_FOUND,
    LOCAL_REF_NOT_APPLIED,
    LOCAL_REF_ENTITY_TYPE_MISMATCH,
    LOCAL_REF_CIRCULAR_DEPENDENCY,
    LOCAL_REF_FORWARD_REFERENCE_NOT_ALLOWED,
    LOCAL_REF_FAILED_DEPENDENCY,
    PAYLOAD_TOO_LARGE,
    BATCH_PAYLOAD_TOO_LARGE,
    TOO_MANY_ITEMS,
    TOO_MANY_COMMANDS,
    DEPENDENCY_DEPTH_EXCEEDED
}
