package com.restaurante.model.enums;

public enum DeviceOfflineConflictCode {
    PAYLOAD_HASH_MISMATCH,
    ENTITY_NOT_FOUND,
    SESSION_CLOSED,
    PRODUCT_INACTIVE,
    PRICE_CHANGED,
    PAYMENT_METHOD_NOT_ALLOWED,
    TURNO_NOT_OPEN,
    ORDER_ALREADY_CONFIRMED,
    DEVICE_NOT_AUTHORIZED,
    COMMAND_TYPE_NOT_ALLOWED_OFFLINE,
    IDEMPOTENCY_CONFLICT
}

