package com.restaurante.model.enums;

public enum DeviceCapability {
    HEARTBEAT,
    SYNC_CATALOG,
    VIEW_ORDERS,
    CREATE_ORDER,
    VIEW_PRODUCTION,
    UPDATE_PRODUCTION_STATUS,
    VIEW_PAYMENTS,
    INITIATE_PAYMENT,
    VIEW_PAYMENT_ORDER,
    CONFIRM_CASH_PAYMENT,
    CONFIRM_TPA_PAYMENT,
    MANAGE_CONSUMPTION_FUND,
    REPRINT_CONSUMPTION_DOCUMENTS,
    PRINT_RECEIPT,
    // Prompt 39.2: identificação assistida (sensível)
    LOOKUP_CONSUMPTION_BY_PHONE,
    REQUEST_ASSISTED_IDENTIFICATION_OTP,
    VERIFY_ASSISTED_IDENTIFICATION_OTP,
    LINK_CUSTOMER_TO_SESSION,
    CROSS_UNIT_ASSISTED_IDENTIFICATION,
    // Prompt 40: POS offline-first mínimo (sync seguro de comandos)
    OFFLINE_SYNC,
    OFFLINE_CREATE_ORDER,
    OFFLINE_CREATE_MANUAL_PAYMENT_ORDER,
    OFFLINE_CONFIRM_MANUAL_PAYMENT,
    // Prompt 41.1: gestão assistida de participantes no POS/device
    VIEW_SESSION_PARTICIPANTS,
    ADD_SESSION_PARTICIPANT,
    REMOVE_SESSION_PARTICIPANT,
    PROMOTE_SESSION_PARTICIPANT,
    DEMOTE_SESSION_PARTICIPANT,
    BLOCK_SESSION_PARTICIPANT,
    RESTORE_SESSION_PARTICIPANT,
    MANAGE_SESSION_PARTICIPANTS,
    // Prompt 41.2: política de entrada + aprovação/convite
    VIEW_PENDING_SESSION_PARTICIPANTS,
    APPROVE_SESSION_PARTICIPANT,
    REJECT_SESSION_PARTICIPANT,
    CHANGE_SESSION_ENTRY_POLICY,
    INVITE_SESSION_PARTICIPANT,
    // Prompt 41.3: ciclo de vida (cancelamento/reenvio/expiração manual)
    CANCEL_SESSION_PARTICIPANT_INVITE,
    RESEND_SESSION_PARTICIPANT_INVITE,
    EXPIRE_SESSION_PARTICIPANT_MANUALLY,
    // Prompt 42: caixa por operador/device (reconciliação CASH/TPA)
    OPEN_OPERATOR_CASH_SESSION,
    CLOSE_OPERATOR_CASH_SESSION,
    VIEW_OPERATOR_CASH_SESSION,
    VIEW_OPERATOR_CASH_SESSION_ITEMS,
    REVIEW_OPERATOR_CASH_SESSION,
    // Prompt 42.2: divergências/ajustes formais de caixa
    VIEW_OPERATOR_CASH_DIVERGENCE,
    JUSTIFY_OPERATOR_CASH_DIVERGENCE,
    SUBMIT_OPERATOR_CASH_DIVERGENCE,
    REVIEW_OPERATOR_CASH_DIVERGENCE,
    VIEW_OPERATOR_CASH_ADJUSTMENT
}
