package com.restaurante.model.enums;

public enum DeviceCapability {
    HEARTBEAT,
    SYNC_CATALOG,
    VIEW_ORDERS,
    CREATE_ORDER,
    VIEW_PRODUCTION,
    UPDATE_PRODUCTION_STATUS,
    VIEW_PAYMENTS,
    INITIATE_PAYMENT,
    VIEW_PAYMENT_ORDER,
    CONFIRM_CASH_PAYMENT,
    CONFIRM_TPA_PAYMENT,
    MANAGE_CONSUMPTION_FUND,
    REPRINT_CONSUMPTION_DOCUMENTS,
    PRINT_RECEIPT
}
