package com.restaurante.model.enums;

public enum InventoryMovementType {
    PURCHASE_IN,
    SALE_CONSUMPTION,
    RETURN_IN,
    CONSUMPTION_REVERSAL_IN,
    RETURN_WASTE,
    COGS_REVERSAL_ONLY,
    WASTE,
    ADJUSTMENT_IN,
    ADJUSTMENT_OUT,
    TRANSFER_IN,
    TRANSFER_OUT,
    PRODUCTION_IN,
    PRODUCTION_CONSUMPTION
}
