package com.restaurante.model.enums;

public enum OperationalEventType {
    PEDIDO_STATUS_CHANGED,
    SUBPEDIDO_STATUS_CHANGED,
    TRANSITION_BLOCKED,

    TURNO_ABERTO,
    TURNO_FECHO_INICIADO,
    TURNO_FECHADO,
    TURNO_FECHADO_FORCADO,
    TURNO_CANCELADO,
    CHECKLIST_ABERTURA_CONCLUIDO,
    CHECKLIST_FECHO_CONCLUIDO,
    PEDIDO_SEM_TURNO_ABERTO
}
