package com.restaurante.model.enums;

public enum OperationalEntityType {
    PEDIDO,
    SUBPEDIDO,
    ITEM_PEDIDO,
    SESSAO_CONSUMO,
    CLIENTE_CONSUMO,
    TELEFONE_OTP_CHALLENGE,
    DISPOSITIVO_OPERACIONAL,
    DEVICE_CAPABILITY,
    MESA,
    PAGAMENTO,
    ORDEM_PAGAMENTO,
    TENANT_PAYMENT_METHOD,
    UNIDADE_PAYMENT_METHOD_POLICY,
    DEVICE_PAYMENT_METHOD_POLICY,
    PAYMENT_POLICY_TEMPLATE,
    PAYMENT_POLICY_ROLLOUT,
    FUNDO_CONSUMO,
    TURNO_OPERACIONAL,
    CHECKLIST_OPERACIONAL,
    DEVICE_OFFLINE_COMMAND,
    DEVICE_OFFLINE_SYNC,
    DEVICE_OFFLINE_REPLAY_OPERATION,
    SESSAO_CONSUMO_PARTICIPANTE,
    CAIXA_OPERADOR_SESSION,
    // Prompt 43: fiscalidade (documento fiscal interno)
    FISCAL_DOCUMENT,
    TENANT_FISCAL_PROFILE,
    TENANT_TAX_POLICY,
    PRODUCT_TAX_CLASSIFICATION,
    // Prompt 43.1: auto-emissão fiscal pós-pagamento
    FISCAL_AUTO_ISSUE_JOB,
    // Prompt 43.2: correções fiscais internas (assessment + notas)
    FISCAL_ADJUSTMENT_ASSESSMENT,
    TENANT_FISCAL_CORRECTION_POLICY,
    // Prompt 45: preparação para faturação eletrónica (camada oficial futura)
    OFFICIAL_FISCAL_PROFILE,
    FISCAL_SIGNING_PROFILE,
    OFFICIAL_FISCAL_SUBMISSION,
    OFFICIAL_FISCAL_SUBMISSION_ATTEMPT,
    // Prompt 44: inventário
    INVENTORY_ITEM,
    UNIT_OF_MEASURE,
    UNIT_CONVERSION,
    TENANT_INVENTORY_POLICY,
    INVENTORY_RECIPE,
    INVENTORY_RECIPE_LINE,
    PRODUCT_INVENTORY_MAPPING,
    INVENTORY_MOVEMENT,
    INVENTORY_CONSUMPTION_RECORD,
    INVENTORY_CONSUMPTION_LINE,
    // Prompt 44.1: devoluções/estornos
    INVENTORY_RETURN_RECORD,
    INVENTORY_RETURN_LINE,

    // Prompt 46: billing / metering / invoice interna SaaS
    BILLING_PLAN,
    TENANT_SUBSCRIPTION,
    BILLING_CYCLE,
    USAGE_EVENT,
    USAGE_AGGREGATION,
    USAGE_ADJUSTMENT,
    TENANT_BILLING_INVOICE,
    TENANT_BILLING_INVOICE_LINE
}
