package com.restaurante.model.enums;

public enum OperationalEventType {
    PEDIDO_STATUS_CHANGED,
    SUBPEDIDO_STATUS_CHANGED,
    TRANSITION_BLOCKED,

    PEDIDO_CRIADO_DEVICE,
    PAGAMENTO_INICIADO_DEVICE,
    PAGAMENTO_POLLING_TENTADO,
    PAGAMENTO_CONFIRMADO_POR_POLLING,
    PAGAMENTO_POLLING_PENDENTE,
    PAGAMENTO_POLLING_EXPIRADO,
    PAGAMENTO_POLLING_FALHOU,
    PAGAMENTO_POLLING_MAX_TENTATIVAS,
    PAGAMENTO_POLLING_DIVERGENCIA_VALOR,

    TURNO_ABERTO,
    TURNO_FECHO_INICIADO,
    TURNO_FECHADO,
    TURNO_FECHADO_FORCADO,
    TURNO_CANCELADO,
    CHECKLIST_ABERTURA_CONCLUIDO,
    CHECKLIST_FECHO_CONCLUIDO,
    PEDIDO_SEM_TURNO_ABERTO
}
