package com.restaurante.model.enums;

public enum OperationalEventType {
    PEDIDO_STATUS_CHANGED,
    SUBPEDIDO_STATUS_CHANGED,
    TRANSITION_BLOCKED,

    PEDIDO_CRIADO_DEVICE,
    PAGAMENTO_INICIADO_DEVICE,
    PAGAMENTO_POLLING_TENTADO,
    PAGAMENTO_CONFIRMADO_POR_POLLING,
    PAGAMENTO_POLLING_PENDENTE,
    PAGAMENTO_POLLING_EXPIRADO,
    PAGAMENTO_POLLING_FALHOU,
    PAGAMENTO_POLLING_MAX_TENTATIVAS,
    PAGAMENTO_POLLING_DIVERGENCIA_VALOR,
    PAGAMENTO_POLLING_MANUAL_SOLICITADO,
    PAGAMENTO_POLLING_MANUAL_EXECUTADO,
    PAGAMENTO_POLLING_MANUAL_BLOQUEADO,
    TURNO_FECHO_BLOQUEADO_ALERTA_FINANCEIRO,
    TURNO_FECHADO_COM_ALERTA_FINANCEIRO,

    TURNO_ABERTO,
    TURNO_FECHO_INICIADO,
    TURNO_FECHADO,
    TURNO_FECHADO_FORCADO,
    TURNO_CANCELADO,
    CHECKLIST_ABERTURA_CONCLUIDO,
    CHECKLIST_FECHO_CONCLUIDO,
    PEDIDO_SEM_TURNO_ABERTO,

    // Prompt 36: Consumo físico + ordens manuais CASH/TPA
    ORDEM_PAGAMENTO_CRIADA,
    ORDEM_PAGAMENTO_CONFIRMADA_MANUAL,
    PAGAMENTO_CASH_CONFIRMADO_DEVICE,
    PAGAMENTO_TPA_CONFIRMADO_DEVICE,
    FUNDO_CONSUMO_CREDITADO_MANUAL,
    FUNDO_CONSUMO_BLOQUEADO,
    FUNDO_CONSUMO_DESBLOQUEADO,
    SESSAO_CONSUMO_ENCERRADA,
    CONSUMO_QR_REIMPRESSO_DEVICE,
    CONTA_REIMPRESSA_DEVICE,
    COMPROVATIVO_ORDEM_REIMPRESSO_DEVICE,

    // Prompt 37.2: Snapshot financeiro com hash + export lógico
    SNAPSHOT_FINANCEIRO_HASH_GERADO,
    SNAPSHOT_FINANCEIRO_EXPORTADO,
    SNAPSHOT_FINANCEIRO_INTEGRIDADE_INVALIDA,
    SNAPSHOT_FINANCEIRO_ASSINATURA_GERADA,
    SNAPSHOT_FINANCEIRO_ASSINATURA_INVALIDA,
    SNAPSHOT_FINANCEIRO_EVIDENCE_BUNDLE_EXPORTADO,
    SNAPSHOT_FINANCEIRO_KEY_ROTATION_VERIFICADA,
    SNAPSHOT_FINANCEIRO_KEY_ID_DESCONHECIDO,
    SNAPSHOT_FINANCEIRO_KEY_DISABLED,

    // Prompt 37.5/37.6: Evidence bundle persistido + cadeia de custódia + WORM lógico
    EVIDENCE_BUNDLE_PERSISTIDO,
    EVIDENCE_BUNDLE_EXPORTADO,
    EVIDENCE_BUNDLE_VERIFICADO,
    EVIDENCE_BUNDLE_INTEGRIDADE_INVALIDA,
    EVIDENCE_BUNDLE_CHAIN_INVALIDA,
    EVIDENCE_BUNDLE_RETENTION_APLICADA,
    EVIDENCE_BUNDLE_RETENTION_EXPIRED,
    EVIDENCE_BUNDLE_WORM_LOCK_APLICADO
}
