package com.restaurante.model.enums;

public enum OtpPurpose {
    IDENTIFICAR_SESSAO,
    RECUPERAR_SESSAO,
    VINCULAR_TELEFONE,
    POS_VINCULAR_SESSAO,
    ENTRAR_SESSAO_COMPARTILHADA,
    POS_ADICIONAR_PARTICIPANTE_SESSAO,
    OWNER_APPROVAL_AUTH,
    ACEITAR_CONVITE_SESSAO
}
