package com.restaurante.model.enums;

public enum PaymentMethodPolicyRolloutSkippedReason {
    EXISTING_POLICY_SKIP_MODE,
    CANCELLED_BY_USER,
    MANUAL_OVERRIDE_PROTECTED,
    MAX_ATTEMPTS_EXCEEDED,
    STALE_LOCK_RECOVERED,
    BACKOFF_PENDING,
    RERUN_RESET,
    TEMPLATE_ITEM_NOT_APPLICABLE,
    DEVICE_NOT_TARGETED,
    TENANT_OR_UNIDADE_BLOCKS_EFFECTIVE_USE,
    POLICY_ALREADY_MATCHES
}
