package com.restaurante.model.enums;

public enum TenantAuditAction {
    TENANT_USER_CREATED,
    TENANT_USER_REUSED,
    TENANT_USER_ROLES_CHANGED,
    TENANT_USER_SUSPENDED,
    TENANT_USER_REACTIVATED,
    TENANT_USER_REMOVED,
    TENANT_USER_LIMIT_EXCEEDED,
    TENANT_USER_ACTION_FORBIDDEN
}

