package com.restaurante.model.enums;

public enum UsageMetricCode {
    PAYMENT_CONFIRMED,
    PAID_ORDER,
    APPYPAY_PAYMENT_CONFIRMED,
    MANUAL_PAYMENT_CONFIRMED,
    FISCAL_DOCUMENT_ISSUED,
    OFFICIAL_FISCAL_SUBMISSION_CREATED,
    ACTIVE_DEVICE_DAY,
    ACTIVE_UNIT_DAY,
    INVENTORY_CONSUMPTION_PROCESSED,
    RETURN_PROCESSED
}

