-- CONSUMA baseline schema
-- Generated from current JPA/Hibernate metadata before Tenant Core refactor
-- Date: 2026-05-17
-- Do not edit manually unless reviewed
create table atendentes (ativo boolean not null, created_at timestamp(6) not null, id bigserial not null, updated_at timestamp(6), version bigint, telefone varchar(20), created_by varchar(100), email varchar(100) not null unique, modified_by varchar(100), nome varchar(100) not null, senha varchar(255) not null, tipo_usuario varchar(255) not null check (tipo_usuario in ('CLIENTE','ATENDENTE','COZINHA','GERENTE','ADMIN')), primary key (id));
create table categoria_produtos (ativo boolean not null, ordem integer not null, created_at timestamp(6) not null, id bigserial not null, tenant_id bigint not null, updated_at timestamp(6), version bigint, slug varchar(80) not null, created_by varchar(100), modified_by varchar(100), nome varchar(150) not null, descricao TEXT, primary key (id), constraint uk_categoria_produto_tenant_slug unique (tenant_id, slug));
create table clientes (ativo boolean not null, telefone_verificado boolean not null, created_at timestamp(6) not null, id bigserial not null, otp_expiration timestamp(6), updated_at timestamp(6), version bigint, otp_code varchar(10), telefone varchar(20) not null unique, created_by varchar(100), modified_by varchar(100), nome varchar(100), tipo_usuario varchar(255) not null check (tipo_usuario in ('CLIENTE','ATENDENTE','COZINHA','GERENTE','ADMIN')), primary key (id));
create table configuracao_financeira_event_log (flag_anterior boolean, flag_novo boolean, valor_anterior numeric(14,2), valor_novo numeric(14,2), entidade_id bigint, id bigserial not null, timestamp timestamp(6) not null, usuario_role varchar(50) not null, entidade_tipo varchar(60), tipo_evento varchar(60) not null, usuario_nome varchar(100) not null, detalhe varchar(500), motivo varchar(500), primary key (id));
create table configuracao_financeira_sistema (limite_pos_pago numeric(10,2) not null, pos_pago_ativo boolean not null, valor_minimo_operacao numeric(10,2) not null, created_at timestamp(6) not null, id bigserial not null, updated_at timestamp(6), version bigint, atualizado_por_role varchar(50), atualizado_por_nome varchar(100), created_by varchar(100), modified_by varchar(100), motivo_ultima_alteracao varchar(500), primary key (id));
create table cozinhas (ativa boolean not null, created_at timestamp(6) not null, id bigserial not null, updated_at timestamp(6), version bigint, tipo varchar(30) not null check (tipo in ('CENTRAL','BAR_PREP','CONFEITARIA','GRILL','PIZZARIA','SUSHI','ESPECIAL')), impressora_id varchar(50), created_by varchar(100), modified_by varchar(100), nome varchar(100) not null, descricao varchar(500), primary key (id));
create table dispositivos_operacionais (activation_code_expires_at timestamp(6), ativado_em timestamp(6), created_at timestamp(6) not null, device_token_issued_at timestamp(6), device_token_revoked_at timestamp(6), id bigserial not null, instituicao_id bigint not null, revogado_em timestamp(6), tenant_id bigint not null, ultimo_heartbeat_em timestamp(6), unidade_atendimento_id bigint, updated_at timestamp(6), version bigint, platform varchar(30), status varchar(30) not null check (status in ('PENDENTE_ATIVACAO','ATIVO','SUSPENSO','REVOGADO','EXPIRADO')), tipo varchar(30) not null check (tipo in ('POS','KDS','CHECKOUT','COZINHA','BAR','BALCAO','QUIOSQUE','ADMIN','OUTRO')), app_version varchar(40), codigo varchar(60) not null, activation_code_hash varchar(64), device_token_hash varchar(64), serial_hash varchar(64), ultimo_ip varchar(64), fabricante varchar(80), modelo_dispositivo varchar(80), created_by varchar(100), modified_by varchar(100), nome varchar(120) not null, user_agent varchar(255), primary key (id));
create table eventos_sessao (created_at timestamp(6) not null, id bigserial not null, sessao_consumo_id bigint not null, updated_at timestamp(6), version bigint, tipo_evento varchar(50) not null check (tipo_evento in ('SESSAO_ABERTA','MESA_VINCULADA','MESA_DESVINCULADA','CLIENTE_VINCULADO','PEDIDO_CRIADO','FUNDO_RECARREGADO','FUNDO_DEBITADO','PAGAMENTO_SOLICITADO','SESSAO_ENCERRADA','SESSAO_EXPIRADA_AUTOMATICAMENTE','OUTRO')), created_by varchar(100), modified_by varchar(100), descricao TEXT, usuario_responsavel varchar(255), primary key (id));
create table fundos_consumo (ativo boolean not null, saldo_atual numeric(19,2), created_at timestamp(6) not null, id bigserial not null, sessao_consumo_id bigint not null unique, updated_at timestamp(6), version bigint, created_by varchar(100), modified_by varchar(100), primary key (id));
create table instituicoes (ativa boolean not null, created_at timestamp(6) not null, id bigserial not null, otp_expiration timestamp(6), tenant_id bigint not null, updated_at timestamp(6), version bigint, otp_code varchar(10), sigla varchar(10) not null unique, telefone_autorizacao varchar(20) not null, nif varchar(50) not null unique, created_by varchar(100), modified_by varchar(100), nome varchar(150) not null, url_logo varchar(500), primary key (id));
create table itens_pedido (preco_unitario numeric(10,2) not null, quantidade integer not null check (quantidade>=1), subtotal numeric(10,2) not null, created_at timestamp(6) not null, id bigserial not null, pedido_id bigint, produto_id bigint not null, sub_pedido_id bigint not null, tenant_id bigint not null, updated_at timestamp(6), version bigint, created_by varchar(100), modified_by varchar(100), observacoes varchar(500), primary key (id));
create table mesas (ativa boolean not null, capacidade integer, numero integer, created_at timestamp(6) not null, id bigserial not null, instituicao_id bigint, tenant_id bigint not null, unidade_atendimento_id bigint not null, updated_at timestamp(6), version bigint, tipo varchar(30) not null check (tipo in ('MESA_FISICA','QUARTO','AREA_EVENTO','ESPACO_LOUNGE','VIRTUAL')), created_by varchar(100), modified_by varchar(100), qr_code varchar(100) unique, referencia varchar(100) not null, primary key (id));
create table pagamento_callback_logs (processed boolean not null, signature_valid boolean, created_at timestamp(6) not null, id bigserial not null, pagamento_id bigint, processed_at timestamp(6), received_at timestamp(6) not null, tenant_id bigint, updated_at timestamp(6), version bigint, external_reference varchar(15), processing_status varchar(30) not null check (processing_status in ('RECEIVED','PROCESSED','IGNORED_DUPLICATE','FAILED','INVALID_SIGNATURE','PAYMENT_NOT_FOUND')), provider varchar(30) not null, status_recebido varchar(40), created_by varchar(100), gateway_charge_id varchar(100), modified_by varchar(100), processing_error varchar(500), headers_json TEXT, payload_json TEXT, raw_body TEXT, primary key (id));
create table pagamento_event_log (id bigserial not null, pagamento_id bigint, pedido_id bigint, timestamp timestamp(6) not null, ip varchar(50), role varchar(50) not null, tipo_evento varchar(50) not null check (tipo_evento in ('PAGAMENTO_CRIADO','CONFIRMACAO_PAGAMENTO','CALLBACK_RECEBIDO','AUTORIZACAO_POS_PAGO','NEGACAO_POS_PAGO','ESTORNO_MANUAL','ESTORNO_AUTOMATICO','POLITICA_POS_PAGO_ATIVADA','POLITICA_POS_PAGO_DESATIVADA','RECARGA_FUNDO','PAGAMENTO_FALHOU')), usuario varchar(100) not null, motivo varchar(500), dados_adicionais TEXT, primary key (id));
create table pagamentos_gateway (amount numeric(10,2) not null, cliente_id bigint, confirmed_at timestamp(6), created_at timestamp(6) not null, fundo_consumo_id bigint, id bigserial not null, pedido_id bigint, tenant_id bigint not null, updated_at timestamp(6), version bigint, entidade varchar(10), external_reference varchar(15) unique, metodo varchar(20) check (metodo in ('GPO','REF')), referencia varchar(20), status varchar(20) not null check (status in ('PENDENTE','CONFIRMADO','FALHOU','ESTORNADO')), tipo_pagamento varchar(20) not null check (tipo_pagamento in ('PRE_PAGO','POS_PAGO')), created_by varchar(100), gateway_charge_id varchar(100), modified_by varchar(100), observacoes varchar(500), gateway_response TEXT, primary key (id));
create table pedido_event_log (created_at timestamp(6) not null, id bigserial not null, pedido_id bigint not null, timestamp timestamp(6) not null, ip_origem varchar(50), usuario varchar(100), observacoes varchar(500), status_anterior varchar(255) check (status_anterior in ('CRIADO','EM_ANDAMENTO','FINALIZADO','CANCELADO')), status_novo varchar(255) not null check (status_novo in ('CRIADO','EM_ANDAMENTO','FINALIZADO','CANCELADO')), primary key (id));
create table pedido_sequence_counters (data_referencia date not null, created_at timestamp(6) not null, id bigserial not null, proximo_numero bigint not null, tenant_id bigint not null, updated_at timestamp(6), version bigint, created_by varchar(100), modified_by varchar(100), primary key (id));
create table pedidos (total numeric(10,2), created_at timestamp(6) not null, id bigserial not null, pago_em timestamp(6), sessao_consumo_id bigint not null, tenant_id bigint not null, updated_at timestamp(6), version bigint, status varchar(20) not null check (status in ('CRIADO','EM_ANDAMENTO','FINALIZADO','CANCELADO')), status_financeiro varchar(20) not null check (status_financeiro in ('NAO_PAGO','PENDENTE_PAGAMENTO','PAGO','ESTORNADO')), tipo_pagamento varchar(20) not null check (tipo_pagamento in ('PRE_PAGO','POS_PAGO')), created_by varchar(100), modified_by varchar(100), observacoes varchar(500), numero varchar(255) not null unique, primary key (id));
create table planos (ativo boolean not null, max_dispositivos integer not null, max_instituicoes integer not null, max_produtos integer not null, max_qr_codes integer not null, max_unidades_atendimento integer not null, max_usuarios integer not null, permite_multi_instituicao boolean not null, permite_offline boolean not null, permite_pedidos_qr boolean not null, permite_pos boolean not null, preco_mensal numeric(12,2) not null, created_at timestamp(6) not null, id bigserial not null, updated_at timestamp(6), version bigint, codigo varchar(30) not null unique, created_by varchar(100), modified_by varchar(100), nome varchar(120) not null, descricao TEXT, primary key (id));
create table produtos (ativo boolean not null, disponivel boolean not null, preco numeric(10,2) not null, tempo_preparo_minutos integer, categoria_produto_id bigint not null, created_at timestamp(6) not null, id bigserial not null, tenant_id bigint not null, updated_at timestamp(6), version bigint, categoria varchar(30) not null check (categoria in ('ENTRADA','PRATO_PRINCIPAL','ACOMPANHAMENTO','SOBREMESA','BEBIDA_ALCOOLICA','BEBIDA_NAO_ALCOOLICA','LANCHE','PIZZA','OUTROS')), codigo varchar(50) not null, created_by varchar(100), modified_by varchar(100), nome varchar(150) not null, descricao varchar(500), url_imagem varchar(500), primary key (id), constraint idx_produto_tenant_codigo unique (tenant_id, codigo));
create table provisioning_templates (ativo boolean not null, created_at timestamp(6) not null, id bigserial not null, updated_at timestamp(6), version bigint, tipo_tenant varchar(40) not null check (tipo_tenant in ('VENDEDOR_RUA','RESTAURANTE','BAR','FOOD_COURT','EVENTO','LOJA','CLUBE','INSTITUCIONAL')), codigo varchar(60) not null unique, created_by varchar(100), modified_by varchar(100), nome varchar(120) not null, descricao varchar(500), configuracao_json TEXT, primary key (id));
create table public_qr_order_requests (created_at timestamp(6) not null, id bigserial not null, pedido_id bigint, qr_code_operacional_id bigint not null, tenant_id bigint not null, updated_at timestamp(6), version bigint, status varchar(20) not null check (status in ('PROCESSING','COMPLETED','FAILED')), request_hash varchar(64) not null, created_by varchar(100), idempotency_key varchar(100) not null, modified_by varchar(100), primary key (id));
create table public_qr_payment_requests (created_at timestamp(6) not null, id bigserial not null, pagamento_id bigint, pedido_id bigint not null, tenant_id bigint not null, updated_at timestamp(6), version bigint, status varchar(20) not null check (status in ('PROCESSING','COMPLETED','FAILED')), request_hash varchar(64) not null, created_by varchar(100), idempotency_key varchar(100) not null, modified_by varchar(100), primary key (id));
create table qr_code_tokens (created_at timestamp(6) not null, expira_em timestamp(6) not null, id bigserial not null, instituicao_id bigint, mesa_id bigint, pedido_id bigint, updated_at timestamp(6), usado_em timestamp(6), version bigint, status varchar(20) not null check (status in ('ATIVO','USADO','EXPIRADO','CANCELADO')), tipo varchar(20) not null check (tipo in ('MESA','ENTREGA','PAGAMENTO')), token varchar(36) not null unique, created_by varchar(100), modified_by varchar(100), usado_por varchar(100), metadados TEXT, primary key (id));
create table qr_codes_operacionais (ativo boolean not null, revogado boolean not null, created_at timestamp(6) not null, id bigserial not null, instituicao_id bigint not null, mesa_id bigint, revogado_em timestamp(6), tenant_id bigint not null, unidade_atendimento_id bigint, updated_at timestamp(6), version bigint, tipo varchar(30) not null check (tipo in ('TENANT_GERAL','INSTITUICAO','UNIDADE_ATENDIMENTO','MESA','BALCAO','TAKEAWAY','DELIVERY','EVENTO','QUIOSQUE')), token varchar(64) not null unique, created_by varchar(100), modified_by varchar(100), nome varchar(120), primary key (id));
create table rotas_producao_categoria (ativo boolean not null, prioridade integer not null, atualizado_em timestamp(6), categoria_produto_id bigint not null, created_at timestamp(6) not null, criado_em timestamp(6) not null, id bigserial not null, tenant_id bigint not null, unidade_producao_id bigint not null, updated_at timestamp(6), version bigint, created_by varchar(100), modified_by varchar(100), primary key (id));
create table sessoes_consumo (modo_anonimo boolean not null, aberta_em timestamp(6) not null, atendente_id bigint, cliente_id bigint, created_at timestamp(6) not null, fechada_em timestamp(6), id bigserial not null, instituicao_id bigint, mesa_id bigint, tenant_id bigint not null, ultima_atividade_em timestamp(6) not null, unidade_atendimento_id bigint, updated_at timestamp(6), version bigint, tipo_sessao varchar(20) not null check (tipo_sessao in ('PRE_PAGO','POS_PAGO')), status varchar(30) not null check (status in ('ABERTA','AGUARDANDO_PAGAMENTO','ENCERRADA','EXPIRADA')), qr_code_sessao varchar(36) not null unique, created_by varchar(100), modified_by varchar(100), primary key (id));
create table sub_pedidos (total numeric(10,2), cozinha_id bigint not null, created_at timestamp(6) not null, entregue_em timestamp(6), id bigserial not null, iniciado_em timestamp(6), pedido_id bigint not null, pronto_em timestamp(6), recebido_em timestamp(6), tenant_id bigint not null, unidade_atendimento_id bigint not null, unidade_producao_id bigint, updated_at timestamp(6), version bigint, status varchar(20) not null check (status in ('CRIADO','PENDENTE','EM_PREPARACAO','PRONTO','ENTREGUE','CANCELADO')), numero varchar(50) not null unique, created_by varchar(100), modified_by varchar(100), responsavel_entrega varchar(100), responsavel_preparo varchar(100), observacoes varchar(500), primary key (id));
create table subpedido_event_log (cozinha_id bigint not null, created_at timestamp(6) not null, id bigserial not null, subpedido_id bigint not null, tempo_transacao_ms bigint, timestamp timestamp(6) not null, ip_origem varchar(50), usuario varchar(100), observacoes varchar(500), status_anterior varchar(255) check (status_anterior in ('CRIADO','PENDENTE','EM_PREPARACAO','PRONTO','ENTREGUE','CANCELADO')), status_novo varchar(255) not null check (status_novo in ('CRIADO','PENDENTE','EM_PREPARACAO','PRONTO','ENTREGUE','CANCELADO')), primary key (id));
create table subscricoes (fim_em date, inicio_em date not null, renovacao_automatica boolean not null, created_at timestamp(6) not null, id bigserial not null, plano_id bigint not null, tenant_id bigint not null, updated_at timestamp(6), version bigint, estado varchar(20) not null check (estado in ('ATIVA','EXPIRADA','SUSPENSA','CANCELADA')), created_by varchar(100), modified_by varchar(100), primary key (id));
create table tenant_audit_logs (actor_user_id bigint not null, created_at timestamp(6) not null, entity_id bigint, id bigserial not null, target_user_id bigint, tenant_id bigint not null, updated_at timestamp(6), version bigint, status varchar(20) not null check (status in ('SUCCESS','FAILURE','BLOCKED')), action varchar(60) not null check (action in ('TENANT_USER_CREATED','TENANT_USER_REUSED','TENANT_USER_ROLES_CHANGED','TENANT_USER_SUSPENDED','TENANT_USER_REACTIVATED','TENANT_USER_REMOVED','TENANT_USER_LIMIT_EXCEEDED','TENANT_USER_ACTION_FORBIDDEN')), entity_type varchar(60) not null, ip varchar(64), created_by varchar(100), modified_by varchar(100), message varchar(500), metadata_json text, user_agent varchar(255), primary key (id));
create table tenant_limite_overrides (ativo boolean not null, max_dispositivos integer, max_instituicoes integer, max_produtos integer, max_qr_codes integer, max_unidades_atendimento integer, max_usuarios integer, configurado_em timestamp(6), created_at timestamp(6) not null, id bigserial not null, tenant_id bigint not null, updated_at timestamp(6), version bigint, created_by varchar(100), modified_by varchar(100), configurado_por varchar(120), motivo varchar(500), primary key (id));
create table tenant_users (created_at timestamp(6) not null, id bigserial not null, tenant_id bigint not null, unidade_atendimento_default_id bigint, updated_at timestamp(6), user_id bigint not null, version bigint, estado varchar(20) not null check (estado in ('ATIVO','PENDENTE','SUSPENSO','REMOVIDO')), role varchar(30) not null check (role in ('TENANT_OWNER','TENANT_ADMIN','TENANT_OPERATOR','TENANT_FINANCE','TENANT_KITCHEN','TENANT_CASHIER')), created_by varchar(100), modified_by varchar(100), primary key (id));
create table tenants (created_at timestamp(6) not null, id bigserial not null, updated_at timestamp(6), version bigint, estado varchar(20) not null check (estado in ('RASCUNHO','ATIVO','SUSPENSO','BLOQUEADO','CANCELADO')), telefone varchar(20), tenant_code varchar(20) not null unique, nif varchar(30), tipo varchar(40) not null check (tipo in ('VENDEDOR_RUA','RESTAURANTE','BAR','FOOD_COURT','EVENTO','LOJA','CLUBE','INSTITUCIONAL')), slug varchar(80) not null unique, created_by varchar(100), modified_by varchar(100), email varchar(120), nome varchar(160) not null, primary key (id));
create table transacoes_fundo (saldo_anterior numeric(19,2) not null, saldo_novo numeric(19,2) not null, valor numeric(19,2) not null, created_at timestamp(6) not null, fundo_consumo_id bigint not null, id bigserial not null, pedido_id bigint, updated_at timestamp(6), version bigint, tipo varchar(20) not null check (tipo in ('CREDITO','DEBITO','ESTORNO','AJUSTE')), created_by varchar(100), merchant_transaction_id varchar(100) unique, modified_by varchar(100), observacoes varchar(500), primary key (id));
create table unidade_cozinha (cozinha_id bigint not null, unidade_id bigint not null);
create table unidades_atendimento (ativa boolean not null, created_at timestamp(6) not null, id bigserial not null, instituicao_id bigint, updated_at timestamp(6), version bigint, tipo varchar(30) not null check (tipo in ('RESTAURANTE','BAR','CAFETERIA','ROOM_SERVICE','EVENTO','PISCINA','LOUNGE')), created_by varchar(100), modified_by varchar(100), nome varchar(100) not null, descricao varchar(500), primary key (id));
create table unidades_consumo (capacidade integer, modo_anonimo boolean not null, numero integer, aberta_em timestamp(6) not null, atendente_id bigint, cliente_id bigint, created_at timestamp(6) not null, fechada_em timestamp(6), id bigserial not null, unidade_atendimento_id bigint not null, updated_at timestamp(6), version bigint, status varchar(30) not null check (status in ('DISPONIVEL','OCUPADA','AGUARDANDO_PAGAMENTO','FINALIZADA')), tipo varchar(30) not null check (tipo in ('MESA_FISICA','QUARTO','AREA_EVENTO','ESPACO_LOUNGE','VIRTUAL')), created_by varchar(100), modified_by varchar(100), qr_code varchar(100) unique, referencia varchar(100) not null, primary key (id));
create table unidades_producao (ativo boolean not null, ordem integer not null, atualizado_em timestamp(6), created_at timestamp(6) not null, criado_em timestamp(6) not null, id bigserial not null, instituicao_id bigint not null, tenant_id bigint not null, unidade_atendimento_id bigint, updated_at timestamp(6), version bigint, tipo varchar(30) not null check (tipo in ('COZINHA','BAR','PASTELARIA','CHURRASQUEIRA','BALCAO','EXPEDICAO','QUIOSQUE','COPA','OUTRO')), codigo varchar(40) not null, created_by varchar(100), modified_by varchar(100), nome varchar(120) not null, primary key (id));
create table user_roles (user_id bigint not null, role varchar(255) check (role in ('ROLE_CLIENTE','ROLE_ATENDENTE','ROLE_GERENTE','ROLE_COZINHA','ROLE_ADMIN')));
create table users (ativo boolean not null, created_at timestamp(6) not null, id bigserial not null, ultimo_acesso timestamp(6), unidade_atendimento_id bigint, updated_at timestamp(6), version bigint, telefone varchar(20) not null unique, username varchar(50) not null unique, created_by varchar(100), email varchar(100) unique, modified_by varchar(100), nome_completo varchar(150), password varchar(255) not null, primary key (id));
create index idx_atendente_telefone on atendentes (telefone);
create index idx_categoria_produto_tenant on categoria_produtos (tenant_id);
create index idx_categoria_produto_ativo on categoria_produtos (tenant_id, ativo);
create index idx_cfg_audit_tipo on configuracao_financeira_event_log (tipo_evento);
create index idx_cfg_audit_usuario on configuracao_financeira_event_log (usuario_nome);
create index idx_cfg_audit_timestamp on configuracao_financeira_event_log (timestamp);
create index idx_cozinha_tipo on cozinhas (tipo);
create index idx_cozinha_ativa on cozinhas (ativa);
create index idx_dispositivo_tenant on dispositivos_operacionais (tenant_id);
create index idx_dispositivo_tenant_status on dispositivos_operacionais (tenant_id, status);
create index idx_dispositivo_tenant_instituicao on dispositivos_operacionais (tenant_id, instituicao_id);
create index idx_dispositivo_tenant_unidade on dispositivos_operacionais (tenant_id, unidade_atendimento_id);
create index idx_dispositivo_device_token_hash on dispositivos_operacionais (device_token_hash);
create index idx_dispositivo_activation_code_hash on dispositivos_operacionais (activation_code_hash);
create index idx_dispositivo_ultimo_heartbeat on dispositivos_operacionais (ultimo_heartbeat_em);
create index idx_evento_sessao on eventos_sessao (sessao_consumo_id);
create index idx_evento_tipo on eventos_sessao (tipo_evento);
create index idx_evento_data on eventos_sessao (created_at);
create index idx_fundo_sessao on fundos_consumo (sessao_consumo_id);
create index idx_fundo_status on fundos_consumo (ativo);
create index idx_fundo_sessao_ativo on fundos_consumo (sessao_consumo_id, ativo);
create index idx_instituicao_ativa on instituicoes (ativa);
create index idx_instituicao_tenant on instituicoes (tenant_id);
create index idx_item_pedido on itens_pedido (pedido_id);
create index idx_item_produto on itens_pedido (produto_id);
create index idx_item_tenant on itens_pedido (tenant_id);
create index idx_mesa_referencia on mesas (referencia);
create index idx_mesa_ativa on mesas (ativa);
create index idx_mesa_unidade_atendimento on mesas (unidade_atendimento_id);
create index idx_mesa_instituicao on mesas (instituicao_id);
create index idx_mesa_tenant on mesas (tenant_id);
create index idx_callback_log_received_at on pagamento_callback_logs (received_at);
create index idx_callback_log_external_ref on pagamento_callback_logs (external_reference);
create index idx_callback_log_pagamento on pagamento_callback_logs (pagamento_id);
create index idx_callback_log_tenant on pagamento_callback_logs (tenant_id);
create index idx_pag_event_pagamento on pagamento_event_log (pagamento_id);
create index idx_pag_event_pedido on pagamento_event_log (pedido_id);
create index idx_pag_event_timestamp on pagamento_event_log (timestamp);
create index idx_pag_event_usuario on pagamento_event_log (usuario);
create index idx_pag_event_tipo on pagamento_event_log (tipo_evento);
create index idx_pagamento_tenant on pagamentos_gateway (tenant_id);
create index idx_pagamento_pedido on pagamentos_gateway (pedido_id);
create index idx_pagamento_fundo on pagamentos_gateway (fundo_consumo_id);
create index idx_pagamento_status on pagamentos_gateway (status);
create index idx_pagamento_external_ref on pagamentos_gateway (external_reference);
create index idx_pagamento_gateway_charge on pagamentos_gateway (gateway_charge_id);
create index idx_pedido_event_pedido on pedido_event_log (pedido_id);
create index idx_pedido_event_timestamp on pedido_event_log (timestamp);
create index idx_pedido_event_usuario on pedido_event_log (usuario);
create index idx_pedido_seq_tenant on pedido_sequence_counters (tenant_id);
create index idx_pedido_sessao_consumo on pedidos (sessao_consumo_id);
create index idx_pedido_status on pedidos (status);
create index idx_pedido_status_financeiro on pedidos (status_financeiro);
create index idx_pedido_numero on pedidos (numero);
create index idx_plano_ativo on planos (ativo);
create index idx_produto_tenant on produtos (tenant_id);
create index idx_produto_tenant_categoria_enum on produtos (tenant_id, categoria);
create index idx_produto_tenant_ativo on produtos (tenant_id, ativo);
create index idx_provisioning_template_ativo on provisioning_templates (ativo);
create index idx_provisioning_template_tipo_tenant on provisioning_templates (tipo_tenant);
create index idx_public_qr_order_tenant_created_at on public_qr_order_requests (tenant_id, created_at);
create index idx_public_qr_order_qr on public_qr_order_requests (qr_code_operacional_id);
create index idx_public_qr_order_pedido on public_qr_order_requests (pedido_id);
create index idx_public_qr_payment_tenant_created_at on public_qr_payment_requests (tenant_id, created_at);
create index idx_public_qr_payment_pedido on public_qr_payment_requests (pedido_id);
create index idx_public_qr_payment_pagamento on public_qr_payment_requests (pagamento_id);
create index idx_qrcode_mesa on qr_code_tokens (mesa_id);
create index idx_qrcode_status on qr_code_tokens (status);
create index idx_qrcode_expiracao on qr_code_tokens (expira_em);
create index idx_qrcode_instituicao on qr_code_tokens (instituicao_id);
create index idx_qr_operacional_tenant on qr_codes_operacionais (tenant_id);
create index idx_qr_operacional_instituicao on qr_codes_operacionais (instituicao_id);
create index idx_qr_operacional_unidade on qr_codes_operacionais (unidade_atendimento_id);
create index idx_qr_operacional_tenant_ativo on qr_codes_operacionais (tenant_id, ativo);
create index idx_qr_operacional_token on qr_codes_operacionais (token);
create index idx_rota_categoria_tenant on rotas_producao_categoria (tenant_id);
create index idx_rota_categoria_tenant_categoria on rotas_producao_categoria (tenant_id, categoria_produto_id);
create index idx_sessao_mesa on sessoes_consumo (mesa_id);
create index idx_sessao_status on sessoes_consumo (status);
create index idx_sessao_cliente on sessoes_consumo (cliente_id);
create index idx_sessao_aberta_em on sessoes_consumo (aberta_em);
create index idx_sessao_instituicao on sessoes_consumo (instituicao_id);
create index idx_sessao_tenant on sessoes_consumo (tenant_id);
create index idx_subpedido_pedido on sub_pedidos (pedido_id);
create index idx_subpedido_cozinha on sub_pedidos (cozinha_id);
create index idx_subpedido_status on sub_pedidos (status);
create index idx_subpedido_unidade on sub_pedidos (unidade_atendimento_id);
create index idx_subpedido_tenant on sub_pedidos (tenant_id);
create index idx_subpedido_event_subpedido on subpedido_event_log (subpedido_id);
create index idx_subpedido_event_cozinha on subpedido_event_log (cozinha_id);
create index idx_subpedido_event_timestamp on subpedido_event_log (timestamp);
create index idx_subpedido_event_usuario on subpedido_event_log (usuario);
create index idx_subscricao_tenant on subscricoes (tenant_id);
create index idx_subscricao_plano on subscricoes (plano_id);
create index idx_subscricao_estado on subscricoes (estado);
create index idx_tenant_audit_logs_tenant on tenant_audit_logs (tenant_id);
create index idx_tenant_audit_logs_actor on tenant_audit_logs (actor_user_id);
create index idx_tenant_audit_logs_target on tenant_audit_logs (target_user_id);
create index idx_tenant_audit_logs_action on tenant_audit_logs (action);
create index idx_tenant_audit_logs_created_at on tenant_audit_logs (created_at);
create index idx_tenant_audit_logs_tenant_created_at on tenant_audit_logs (tenant_id, created_at);
create index idx_tenant_limit_override_tenant on tenant_limite_overrides (tenant_id);
create index idx_tenant_user_tenant on tenant_users (tenant_id);
create index idx_tenant_user_user on tenant_users (user_id);
create index idx_tenant_estado on tenants (estado);
create index idx_transacao_fundo on transacoes_fundo (fundo_consumo_id);
create index idx_transacao_pedido on transacoes_fundo (pedido_id);
create index idx_transacao_tipo on transacoes_fundo (tipo);
create index idx_transacao_merchant_id on transacoes_fundo (merchant_transaction_id);
create index idx_unidade_tipo on unidades_atendimento (tipo);
create index idx_unidade_ativa on unidades_atendimento (ativa);
create index idx_unidade_instituicao on unidades_atendimento (instituicao_id);
create index idx_unidade_consumo_referencia on unidades_consumo (referencia);
create index idx_unidade_consumo_status on unidades_consumo (status);
create index idx_unidade_consumo_cliente on unidades_consumo (cliente_id);
create index idx_unidade_consumo_tipo on unidades_consumo (tipo);
create index idx_unidade_producao_tenant on unidades_producao (tenant_id);
create index idx_unidade_producao_tenant_instituicao on unidades_producao (tenant_id, instituicao_id);
create index idx_unidade_producao_tenant_ativo on unidades_producao (tenant_id, ativo);
create index idx_user_unidade_atendimento on users (unidade_atendimento_id);
alter table if exists categoria_produtos add constraint FKrba9p1kb66ru1ppqpc3j15m2r foreign key (tenant_id) references tenants;
alter table if exists dispositivos_operacionais add constraint FK8jpm1mq9ff6p9slyehvlk7hu1 foreign key (instituicao_id) references instituicoes;
alter table if exists dispositivos_operacionais add constraint FKf4uce2im45o19j737d28grq3k foreign key (tenant_id) references tenants;
alter table if exists dispositivos_operacionais add constraint FKlugo08kwtt90ebrkct8yu36r foreign key (unidade_atendimento_id) references unidades_atendimento;
alter table if exists eventos_sessao add constraint FK7u7a6620kf1jphrytds7cy0bh foreign key (sessao_consumo_id) references sessoes_consumo;
alter table if exists fundos_consumo add constraint FKa8yxml64spwj0bfolkvhbpt2n foreign key (sessao_consumo_id) references sessoes_consumo;
alter table if exists instituicoes add constraint FKsjqgky850sq2fc2pc40187hhk foreign key (tenant_id) references tenants;
alter table if exists itens_pedido add constraint FK42mycompce3b7yt3l6ukdwsxy foreign key (pedido_id) references pedidos;
alter table if exists itens_pedido add constraint FKxytdlekpdaobqphujy9bmuhl foreign key (produto_id) references produtos;
alter table if exists itens_pedido add constraint FKkwliua0isfmea2pgi4p8cj7wt foreign key (sub_pedido_id) references sub_pedidos;
alter table if exists itens_pedido add constraint FKfsc8x4ep6e9ey1d18uhml999 foreign key (tenant_id) references tenants;
alter table if exists mesas add constraint FKlt40g1sws0vhlh3tx1c6ah9rr foreign key (instituicao_id) references instituicoes;
alter table if exists mesas add constraint FKc47002t2h8cqhhslvj1yixop0 foreign key (tenant_id) references tenants;
alter table if exists mesas add constraint FK3p2w52maxnj69o254a5mxb69g foreign key (unidade_atendimento_id) references unidades_atendimento;
alter table if exists pagamento_callback_logs add constraint FKmsmb5qj3jgh8iaiusptj7f12i foreign key (pagamento_id) references pagamentos_gateway;
alter table if exists pagamento_callback_logs add constraint FK9sp0r0iikod10xwduxd1ycdt9 foreign key (tenant_id) references tenants;
alter table if exists pagamento_event_log add constraint FKthrpknml7dcm27eprt907qxgk foreign key (pagamento_id) references pagamentos_gateway;
alter table if exists pagamento_event_log add constraint FK3iirlmsg0bnupbk36r3wmbxrx foreign key (pedido_id) references pedidos;
alter table if exists pagamentos_gateway add constraint FKl4w6p35orykjqgtyfgody3rc2 foreign key (cliente_id) references clientes;
alter table if exists pagamentos_gateway add constraint FKi6a2n80buhwrtqxr31pcglwdn foreign key (fundo_consumo_id) references fundos_consumo;
alter table if exists pagamentos_gateway add constraint FK1v293m131fyl0elcbav82vwnq foreign key (pedido_id) references pedidos;
alter table if exists pagamentos_gateway add constraint FKof0qj0ka9re064fdtmg86n0o2 foreign key (tenant_id) references tenants;
alter table if exists pedido_event_log add constraint FKcg3j42r4vj4kcwqsdy9vv7fo2 foreign key (pedido_id) references pedidos;
alter table if exists pedido_sequence_counters add constraint FKb5pobibrw9xd6sdu4m43ombdu foreign key (tenant_id) references tenants;
alter table if exists pedidos add constraint FKnwb035pg7pd7jj84ap9dvt8ap foreign key (sessao_consumo_id) references sessoes_consumo;
alter table if exists pedidos add constraint FKnd2doo3xnd4mmacnhk1ktq335 foreign key (tenant_id) references tenants;
alter table if exists produtos add constraint FKc75dtsop3epau2kirtcnptjnt foreign key (categoria_produto_id) references categoria_produtos;
alter table if exists produtos add constraint FKdwy9she24lng652omlqi81j9a foreign key (tenant_id) references tenants;
alter table if exists public_qr_order_requests add constraint FKsnhhyu0v2bkex6etl2601j1n0 foreign key (pedido_id) references pedidos;
alter table if exists public_qr_order_requests add constraint FKnv5fpope41gycng5186e9k3wa foreign key (qr_code_operacional_id) references qr_codes_operacionais;
alter table if exists public_qr_order_requests add constraint FKdtps6i3au6apuqyyyfugn1cs1 foreign key (tenant_id) references tenants;
alter table if exists public_qr_payment_requests add constraint FKax2db3kujv3qbnrks3rcdnt1l foreign key (pagamento_id) references pagamentos_gateway;
alter table if exists public_qr_payment_requests add constraint FKs8tvt2joo15kcehaxt3cdv0d4 foreign key (pedido_id) references pedidos;
alter table if exists public_qr_payment_requests add constraint FKo4wf23issc7pcbp4g72o2da6d foreign key (tenant_id) references tenants;
alter table if exists qr_code_tokens add constraint FK393kxtom8wwd231mx0lskuwti foreign key (instituicao_id) references instituicoes;
alter table if exists qr_code_tokens add constraint FKrcwys7j5fs5djry3o7bpw20os foreign key (mesa_id) references mesas;
alter table if exists qr_code_tokens add constraint FKlpped9krjb40wb3o6rlhfox1a foreign key (pedido_id) references pedidos;
alter table if exists qr_codes_operacionais add constraint FK7w6kjqpuaqi54q6dbhx3su6hi foreign key (instituicao_id) references instituicoes;
alter table if exists qr_codes_operacionais add constraint FKbbk8anl1f7mpul7bh39bsyi6w foreign key (mesa_id) references mesas;
alter table if exists qr_codes_operacionais add constraint FK5md0i5diiwcg7bha9w6ct3d7d foreign key (tenant_id) references tenants;
alter table if exists qr_codes_operacionais add constraint FKqc1j1gjxi5dafmw4eiv3bfwdg foreign key (unidade_atendimento_id) references unidades_atendimento;
alter table if exists rotas_producao_categoria add constraint FKik38mjg8m2hgk966playodvvb foreign key (categoria_produto_id) references categoria_produtos;
alter table if exists rotas_producao_categoria add constraint FKpvc035cag6471e7ea3dhkkwpd foreign key (tenant_id) references tenants;
alter table if exists rotas_producao_categoria add constraint FKhw34i030xiu8x5cl8tbo6csmb foreign key (unidade_producao_id) references unidades_producao;
alter table if exists sessoes_consumo add constraint FKs345kdafrtuxlh0633nigc8hs foreign key (atendente_id) references atendentes;
alter table if exists sessoes_consumo add constraint FKjcp00g9wcyeh9c5w0wk0buft1 foreign key (cliente_id) references clientes;
alter table if exists sessoes_consumo add constraint FKavd8rt0lud5qfk8exnkmo95oh foreign key (instituicao_id) references instituicoes;
alter table if exists sessoes_consumo add constraint FKa7w8bgsxqulw88hd8uaa9hdg0 foreign key (mesa_id) references mesas;
alter table if exists sessoes_consumo add constraint FK1l3dio06wx285e4q6v9fjp7yv foreign key (tenant_id) references tenants;
alter table if exists sessoes_consumo add constraint FKladlpe59cp7uert6gro2qa2cv foreign key (unidade_atendimento_id) references unidades_atendimento;
alter table if exists sub_pedidos add constraint FKd94kgp1kft70r2md5gk8fq0hf foreign key (cozinha_id) references cozinhas;
alter table if exists sub_pedidos add constraint FKpqsyh07b6xv30k17lifp7il2n foreign key (pedido_id) references pedidos;
alter table if exists sub_pedidos add constraint FKp99vkuieqc80xg60ucoi2oh0n foreign key (tenant_id) references tenants;
alter table if exists sub_pedidos add constraint FKklyhyblmbjgxkmh7eqgslugy6 foreign key (unidade_atendimento_id) references unidades_atendimento;
alter table if exists sub_pedidos add constraint FKqbg8jwbbw5j7f6ip0dy9qd0lb foreign key (unidade_producao_id) references unidades_producao;
alter table if exists subpedido_event_log add constraint FKem57n1lod6oj1yv314laue4pa foreign key (cozinha_id) references cozinhas;
alter table if exists subpedido_event_log add constraint FKcvt4vdy5o6sf8y63fbb8h06kb foreign key (subpedido_id) references sub_pedidos;
alter table if exists subscricoes add constraint FKlnydin74auphlr40iihokvtpk foreign key (plano_id) references planos;
alter table if exists subscricoes add constraint FK6k60rhholgsgnqvkst5yk5y8w foreign key (tenant_id) references tenants;
alter table if exists tenant_audit_logs add constraint FKaj4jlc5ynb8fovn5iynxn9xd4 foreign key (tenant_id) references tenants;
alter table if exists tenant_limite_overrides add constraint FK7cj2k02yrved70ye4p76nir5q foreign key (tenant_id) references tenants;
alter table if exists tenant_users add constraint FK7tf2f7scsqdlja6wbo80h95wi foreign key (tenant_id) references tenants;
alter table if exists tenant_users add constraint FK6jhk53p0v968ckvsxf6v4uj12 foreign key (unidade_atendimento_default_id) references unidades_atendimento;
alter table if exists tenant_users add constraint FKkd5sv86fojg7ssyc7j8opeaap foreign key (user_id) references users;
alter table if exists transacoes_fundo add constraint FK2hy2kuowah1vsrpg3cc3een8b foreign key (fundo_consumo_id) references fundos_consumo;
alter table if exists transacoes_fundo add constraint FKa19jgq8nh3mb2k3wsnmth75gs foreign key (pedido_id) references pedidos;
alter table if exists unidade_cozinha add constraint FKhawxfa1r8vl612ysjyq1dcd64 foreign key (cozinha_id) references cozinhas;
alter table if exists unidade_cozinha add constraint FKrgvgqrqb7v40o9g2a7ndpgfjx foreign key (unidade_id) references unidades_atendimento;
alter table if exists unidades_atendimento add constraint FK5yf02dq7uatjvj7imdy76bhcl foreign key (instituicao_id) references instituicoes;
alter table if exists unidades_consumo add constraint FKd9tdw32p00byjbxqnd4mng3ru foreign key (atendente_id) references atendentes;
alter table if exists unidades_consumo add constraint FKgoe1uueu4liinpnxoh9yrjb9h foreign key (cliente_id) references clientes;
alter table if exists unidades_consumo add constraint FK2kg9rx7b4ygnukq8ypbt7blpc foreign key (unidade_atendimento_id) references unidades_atendimento;
alter table if exists unidades_producao add constraint FK3b1t9qn1p29op84us6ota5eni foreign key (instituicao_id) references instituicoes;
alter table if exists unidades_producao add constraint FK6tp7hw5rqcuyaf21q5rk5jj04 foreign key (tenant_id) references tenants;
alter table if exists unidades_producao add constraint FKokm5873avglnvdkovwjx441gf foreign key (unidade_atendimento_id) references unidades_atendimento;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FKr16um0be38fa0aijojrq3y0vu foreign key (unidade_atendimento_id) references unidades_atendimento;
