-- Migration: V62__delivery_economics
-- Description: Core tables and fields for delivery economics, courier earnings, reliability score, and settlements.

CREATE TABLE delivery_pricing_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    tenant_id BIGINT,
    scope VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'AOA',
    base_fee_amount NUMERIC(19, 2) NOT NULL DEFAULT 700.00,
    per_km_fee_amount NUMERIC(19, 2) NOT NULL DEFAULT 250.00,
    minimum_fee_amount NUMERIC(19, 2) NOT NULL DEFAULT 1000.00,
    maximum_fee_amount NUMERIC(19, 2),
    consuma_commission_percentage NUMERIC(5, 2) NOT NULL DEFAULT 20.00,
    courier_share_percentage NUMERIC(5, 2) NOT NULL DEFAULT 80.00,
    peak_multiplier NUMERIC(4, 2) NOT NULL DEFAULT 1.00,
    fragile_package_surcharge NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    large_package_surcharge NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    night_surcharge NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    free_delivery_threshold NUMERIC(19, 2),
    tenant_subsidy_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    customer_pays_delivery BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    effective_to TIMESTAMP
);

CREATE TABLE delivery_fee_quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    tenant_id BIGINT NOT NULL,
    pedido_id BIGINT,
    order_fulfillment_id BIGINT,
    delivery_job_id BIGINT,
    pricing_policy_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    distance_km NUMERIC(9, 3) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'AOA',
    base_fee_amount NUMERIC(19, 2) NOT NULL,
    distance_fee_amount NUMERIC(19, 2) NOT NULL,
    surcharge_amount NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    discount_amount NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    tenant_subsidy_amount NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    customer_pays_amount NUMERIC(19, 2) NOT NULL,
    final_delivery_fee_amount NUMERIC(19, 2) NOT NULL,
    courier_earning_amount NUMERIC(19, 2) NOT NULL,
    consuma_commission_amount NUMERIC(19, 2) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    accepted_at TIMESTAMP
);

-- Alter delivery_jobs to add economic columns
ALTER TABLE delivery_jobs ADD COLUMN delivery_fee_quote_id BIGINT;
ALTER TABLE delivery_jobs ADD COLUMN customer_pays_delivery_amount NUMERIC(19, 2);
ALTER TABLE delivery_jobs ADD COLUMN tenant_subsidy_amount NUMERIC(19, 2);
ALTER TABLE delivery_jobs ADD COLUMN courier_earning_amount NUMERIC(19, 2);
ALTER TABLE delivery_jobs ADD COLUMN consuma_commission_amount NUMERIC(19, 2);
ALTER TABLE delivery_jobs ADD COLUMN earning_status VARCHAR(40) NOT NULL DEFAULT 'NOT_EARNED';
ALTER TABLE delivery_jobs ADD COLUMN settlement_status VARCHAR(40) NOT NULL DEFAULT 'NOT_READY';

ALTER TABLE delivery_jobs ADD CONSTRAINT fk_delivery_job_quote FOREIGN KEY (delivery_fee_quote_id) REFERENCES delivery_fee_quotes(id);

CREATE TABLE courier_earnings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    courier_id BIGINT NOT NULL,
    delivery_job_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    pedido_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'AOA',
    delivery_fee_amount NUMERIC(19, 2) NOT NULL,
    courier_earning_amount NUMERIC(19, 2) NOT NULL,
    consuma_commission_amount NUMERIC(19, 2) NOT NULL,
    tenant_subsidy_amount NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    earned_at TIMESTAMP,
    payable_at TIMESTAMP,
    paid_at TIMESTAMP,
    held_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    dispute_reason TEXT
);

CREATE TABLE courier_reliability_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    courier_id BIGINT NOT NULL UNIQUE,
    score INTEGER NOT NULL DEFAULT 100,
    level VARCHAR(40) NOT NULL DEFAULT 'EXCELLENT',
    total_invites INTEGER NOT NULL DEFAULT 0,
    accepted_invites INTEGER NOT NULL DEFAULT 0,
    rejected_invites INTEGER NOT NULL DEFAULT 0,
    missed_invites INTEGER NOT NULL DEFAULT 0,
    expired_invites INTEGER NOT NULL DEFAULT 0,
    completed_deliveries INTEGER NOT NULL DEFAULT 0,
    cancelled_after_accept_count INTEGER NOT NULL DEFAULT 0,
    no_show_count INTEGER NOT NULL DEFAULT 0,
    failed_delivery_count INTEGER NOT NULL DEFAULT 0,
    last_penalty_at TIMESTAMP,
    suspension_until TIMESTAMP
);

CREATE TABLE courier_penalty_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    courier_id BIGINT NOT NULL,
    delivery_job_id BIGINT,
    invite_id BIGINT,
    penalty_type VARCHAR(50) NOT NULL,
    severity VARCHAR(40) NOT NULL,
    points_delta INTEGER NOT NULL,
    reason TEXT NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE courier_penalty_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    missed_invites_24h_pause_threshold INTEGER NOT NULL DEFAULT 3,
    missed_invites_24h_pause_minutes INTEGER NOT NULL DEFAULT 30,
    missed_invites_7d_warning_threshold INTEGER NOT NULL DEFAULT 5,
    missed_invites_7d_suspension_threshold INTEGER NOT NULL DEFAULT 10,
    missed_invites_7d_suspension_hours INTEGER NOT NULL DEFAULT 24,
    no_show_7d_suspension_threshold INTEGER NOT NULL DEFAULT 2,
    no_show_7d_suspension_hours INTEGER NOT NULL DEFAULT 48,
    low_priority_score_threshold INTEGER NOT NULL DEFAULT 74,
    warned_score_threshold INTEGER NOT NULL DEFAULT 59,
    suspended_score_threshold INTEGER NOT NULL DEFAULT 40
);

CREATE TABLE courier_settlement_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    batch_number VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
    period_start TIMESTAMP NOT NULL,
    period_end TIMESTAMP NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'AOA',
    total_earnings_amount NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    total_commission_amount NUMERIC(19, 2) NOT NULL DEFAULT 0.00,
    total_jobs INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE courier_settlement_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    modified_by VARCHAR(100),
    batch_id BIGINT NOT NULL,
    courier_id BIGINT NOT NULL,
    courier_earning_id BIGINT NOT NULL,
    delivery_job_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING'
);

-- Foreign Key Constraints
ALTER TABLE delivery_pricing_policies ADD CONSTRAINT fk_pricing_policy_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE delivery_fee_quotes ADD CONSTRAINT fk_fee_quote_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE delivery_fee_quotes ADD CONSTRAINT fk_fee_quote_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id);
ALTER TABLE delivery_fee_quotes ADD CONSTRAINT fk_fee_quote_fulfillment FOREIGN KEY (order_fulfillment_id) REFERENCES order_fulfillments(id);
ALTER TABLE delivery_fee_quotes ADD CONSTRAINT fk_fee_quote_job FOREIGN KEY (delivery_job_id) REFERENCES delivery_jobs(id);
ALTER TABLE delivery_fee_quotes ADD CONSTRAINT fk_fee_quote_policy FOREIGN KEY (pricing_policy_id) REFERENCES delivery_pricing_policies(id);

ALTER TABLE courier_earnings ADD CONSTRAINT fk_earning_courier FOREIGN KEY (courier_id) REFERENCES courier_profiles(id);
ALTER TABLE courier_earnings ADD CONSTRAINT fk_earning_job FOREIGN KEY (delivery_job_id) REFERENCES delivery_jobs(id);
ALTER TABLE courier_earnings ADD CONSTRAINT fk_earning_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE courier_earnings ADD CONSTRAINT fk_earning_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id);

ALTER TABLE courier_reliability_profiles ADD CONSTRAINT fk_reliability_courier FOREIGN KEY (courier_id) REFERENCES courier_profiles(id);

ALTER TABLE courier_penalty_events ADD CONSTRAINT fk_penalty_courier FOREIGN KEY (courier_id) REFERENCES courier_profiles(id);
ALTER TABLE courier_penalty_events ADD CONSTRAINT fk_penalty_job FOREIGN KEY (delivery_job_id) REFERENCES delivery_jobs(id);
ALTER TABLE courier_penalty_events ADD CONSTRAINT fk_penalty_invite FOREIGN KEY (invite_id) REFERENCES delivery_courier_invites(id);

ALTER TABLE courier_settlement_lines ADD CONSTRAINT fk_settlement_line_batch FOREIGN KEY (batch_id) REFERENCES courier_settlement_batches(id);
ALTER TABLE courier_settlement_lines ADD CONSTRAINT fk_settlement_line_courier FOREIGN KEY (courier_id) REFERENCES courier_profiles(id);
ALTER TABLE courier_settlement_lines ADD CONSTRAINT fk_settlement_line_earning FOREIGN KEY (courier_earning_id) REFERENCES courier_earnings(id);
ALTER TABLE courier_settlement_lines ADD CONSTRAINT fk_settlement_line_job FOREIGN KEY (delivery_job_id) REFERENCES delivery_jobs(id);

-- Indexes for performance
CREATE INDEX idx_delivery_fee_quotes_pedido ON delivery_fee_quotes(pedido_id);
CREATE INDEX idx_courier_earnings_courier ON courier_earnings(courier_id, status);
CREATE INDEX idx_courier_reliability_profiles_courier ON courier_reliability_profiles(courier_id);
CREATE INDEX idx_courier_penalty_events_courier ON courier_penalty_events(courier_id, status);
CREATE INDEX idx_courier_settlement_lines_batch ON courier_settlement_lines(batch_id);

-- Baseline Seeds
INSERT INTO delivery_pricing_policies (scope, status, currency, base_fee_amount, per_km_fee_amount, minimum_fee_amount, consuma_commission_percentage, courier_share_percentage, peak_multiplier, fragile_package_surcharge, large_package_surcharge, night_surcharge, tenant_subsidy_enabled, customer_pays_delivery, effective_from)
VALUES ('GLOBAL', 'ACTIVE', 'AOA', 700.00, 250.00, 1000.00, 20.00, 80.00, 1.00, 0.00, 0.00, 0.00, FALSE, TRUE, CURRENT_TIMESTAMP);

INSERT INTO courier_penalty_policies (status, missed_invites_24h_pause_threshold, missed_invites_24h_pause_minutes, missed_invites_7d_warning_threshold, missed_invites_7d_suspension_threshold, missed_invites_7d_suspension_hours, no_show_7d_suspension_threshold, no_show_7d_suspension_hours, low_priority_score_threshold, warned_score_threshold, suspended_score_threshold)
VALUES ('ACTIVE', 3, 30, 5, 10, 24, 2, 48, 74, 59, 40);
